// Generated by the ProjectIt Language Generator.
import { PiProjection, PiActions } from "@projectit/core";
import { CustomTestCircularImportsActions, CustomTestCircularImportsProjection } from "../editor";
import { TestCircularImportsCheckerInterface } from "../validator/gen";

/**
 * Class ProjectitConfiguration is TODO add comment
 */
class ProjectitConfiguration {
    // add your custom editor projections here
    customProjection: PiProjection[] = [new CustomTestCircularImportsProjection("manual")];
    // add your custom editor actions here
    customActions: PiActions[] = [new CustomTestCircularImportsActions()];
    // add your custom validations here
    customValidations: TestCircularImportsCheckerInterface[] = [];
}

export const projectitConfiguration = new ProjectitConfiguration();
