// Generated by the ProjectIt Language Generator.
import { PiProjection, PiActions } from "@projectit/core";
import { CustomOctopusActions, CustomOctopusProjection } from "../editor";
import { OctopusCheckerInterface } from "../validator/gen";

/**
 * Class ProjectitConfiguration is TODO add comment
 */
class ProjectitConfiguration {
    // add your custom editor projections here
    customProjection: PiProjection[] = [new CustomOctopusProjection("manual")];
    // add your custom editor actions here
    customActions: PiActions[] = [new CustomOctopusActions()];
    // add your custom validations here
    customValidations: OctopusCheckerInterface[] = [];
}

export const projectitConfiguration = new ProjectitConfiguration();
