// Generated by the ProjectIt Language Generator.
import { PiProjection, PiActions } from "@projectit/core";
import { CustomLangConstructsActions, CustomLangConstructsProjection } from "../editor";
import { LangConstructsCheckerInterface } from "../validator/gen";

/**
 * Class ProjectitConfiguration is TODO add comment
 */
class ProjectitConfiguration {
    // add your custom editor projections here
    customProjection: PiProjection[] = [new CustomLangConstructsProjection("manual")];
    // add your custom editor actions here
    customActions: PiActions[] = [new CustomLangConstructsActions()];
    // add your custom validations here
    customValidations: LangConstructsCheckerInterface[] = [];
}

export const projectitConfiguration = new ProjectitConfiguration();
